apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: guelo
    dataset.0.id: "guelo-dataset"
    dataset.0.useas: "mount"
spec:
  containers:
    - name: main-app
      image: alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-ec", "while :; do echo 'Hello Kubernetes! >> /var/teste/guelo.txt'; sleep 10; done"]
      volumeMounts:
      - mountPath: "/var/teste/"
        name: "guelo-dataset"
    - name: nginx
      imagePullPolicy: IfNotPresent
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: "guelo-dataset"
  volumes:
  - name: "guelo-dataset"
    persistentVolumeClaim:
      claimName: "guelo-dataset"